import { Database, Download } from 'lucide-react';
import {
  HardDrive,
  Package,
  Puzzle,
  Server,
} from 'lucide-react';

export const PARKED_FEATURES = [
  { title: 'Downloading', desc: '下载队列与历史页。部署、插件、Mod 下载事件之后可统一汇总到这里。', icon: Download },
  { title: 'Workspace Browser', desc: '工作区文件浏览器仍有旧实现，后续可迁入 Material You 列表。', icon: Database },
];

export const WELCOME_MESSAGES = [
  'Hello! What can I do for you?',
  'Ready to build something amazing?',
  'Need help with your server today?',
  'What are we working on?',
  'How can I assist your Minecraft world?',
  'Got a server task in mind?',
  "Let's make your server better.",
  'What would you like to explore?',
  'Your server assistant is here.',
  'Ask me anything about EasyMC.',
  'What should we set up first?',
  'Ready when you are.',
];

export const DOWNLOAD_TYPES = ['Mods', 'Plugins', 'Server Core'];
export const DOWNLOAD_SOURCE_OPTIONS = [
  { value: 'modrinth', label: 'Modrinth' },
  { value: 'core', label: 'Server Core' },
  { value: 'curseforge', label: 'CurseForge' },
  { value: 'hangar', label: 'Hangar' },
  { value: 'spiget', label: 'Spiget' },
];

export const DOWNLOAD_RESOURCES = [
  {
    id: 'paper-121',
    type: 'Server Core',
    source: 'PaperMC',
    name: 'Paper 1.21.1',
    summary: 'High-performance Bukkit-compatible Minecraft server core.',
    version: '1.21.1 build 132',
    loader: 'Paper',
    target: 'server.jar',
    size: '48.6 MB',
    downloads: 'Core',
    updated: '2026-07-02',
    status: 'Verified',
    icon: Server,
    tags: ['Bukkit API', 'Plugins', 'Performance'],
    details: 'Recommended default server core for plugin-based servers. This sample does not replace your current server files.',
  },
  {
    id: 'fabric-api',
    type: 'Mods',
    source: 'Modrinth',
    name: 'Fabric API',
    summary: 'Core hooks and shared APIs required by many Fabric mods.',
    version: '0.101.2+1.21',
    loader: 'Fabric',
    target: 'mods/',
    size: '2.4 MB',
    downloads: '92M',
    updated: '2026-06-28',
    status: 'Hash available',
    icon: Puzzle,
    tags: ['Dependency', 'Fabric', 'Client+Server'],
    details: 'Common dependency for Fabric servers. The real version resolver will later filter files by Minecraft version and loader.',
  },
  {
    id: 'lithium',
    type: 'Mods',
    source: 'Modrinth',
    name: 'Lithium',
    summary: 'General-purpose server optimization mod without gameplay changes.',
    version: '0.14.8',
    loader: 'Fabric',
    target: 'mods/',
    size: '790 KB',
    downloads: '39M',
    updated: '2026-06-19',
    status: 'Verified',
    icon: Puzzle,
    tags: ['Optimization', 'Server-side', 'Fabric'],
    details: 'Safe performance sample. The final implementation should show dependency and compatibility warnings here.',
  },
  {
    id: 'spark',
    type: 'Plugins',
    source: 'Hangar',
    name: 'spark',
    summary: 'Performance profiler for Minecraft clients, servers, and proxies.',
    version: '1.10.142',
    loader: 'Paper',
    target: 'plugins/',
    size: '3.1 MB',
    downloads: '8M',
    updated: '2026-06-14',
    status: 'Verified',
    icon: Package,
    tags: ['Profiler', 'Diagnostics', 'Paper'],
    details: 'Useful for diagnosing lag. This page only queues a sample item and does not download the plugin yet.',
  },
  {
    id: 'luckperms',
    type: 'Plugins',
    source: 'Modrinth',
    name: 'LuckPerms',
    summary: 'Permissions management plugin for Bukkit, Sponge, Nukkit, and proxies.',
    version: '5.4.158',
    loader: 'Bukkit',
    target: 'plugins/',
    size: '1.7 MB',
    downloads: '24M',
    updated: '2026-05-31',
    status: 'Verified',
    icon: Package,
    tags: ['Permissions', 'Administration', 'Bukkit'],
    details: 'A common server administration plugin. The backend version will ask before replacing existing jars.',
  },
  {
    id: 'purpur-121',
    type: 'Server Core',
    source: 'Purpur',
    name: 'Purpur 1.21.1',
    summary: 'Paper fork with extra gameplay and configuration options.',
    version: '1.21.1 build 2329',
    loader: 'Purpur',
    target: 'server.jar',
    size: '49.2 MB',
    downloads: 'Core',
    updated: '2026-06-25',
    status: 'Mirror ready',
    icon: HardDrive,
    tags: ['Paper fork', 'Configurable', 'Plugins'],
    details: 'Good when you need more server-side toggles than Paper. Core replacement will be a confirmed operation later.',
  },
];
